config/routes.rb
Qawmly::Application.routes.draw do
  resources :users

  resources :trackees

  get "pages/about"
  get "pages/contact"
  get "welcome/index"

   root 'welcome#index'

  resources :tracker

end

app/models/trackee.rb
class Trackee < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/trackees_controller.rb
class TrackeesController < ApplicationController
  before_action :set_trackee, only: [:show, :edit, :update, :destroy]

  # GET /trackees
  # GET /trackees.json
  def index
    @trackees = Trackee.all
  end

  # GET /trackees/1
  # GET /trackees/1.json
  def show
  end

  # GET /trackees/new
  def new
    @trackee = Trackee.new
  end

  # GET /trackees/1/edit
  def edit
  end

  # POST /trackees
  # POST /trackees.json
  def create
    @trackee = Trackee.new(trackee_params)

    respond_to do |format|
      if @trackee.save
        format.html { redirect_to @trackee, notice: 'Trackee was successfully created.' }
        format.json { render action: 'show', status: :created, location: @trackee }
      else
        format.html { render action: 'new' }
        format.json { render json: @trackee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trackees/1
  # PATCH/PUT /trackees/1.json
  def update
    respond_to do |format|
      if @trackee.update(trackee_params)
        format.html { redirect_to @trackee, notice: 'Trackee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @trackee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trackees/1
  # DELETE /trackees/1.json
  def destroy
    @trackee.destroy
    respond_to do |format|
      format.html { redirect_to trackees_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trackee
      @trackee = Trackee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trackee_params
      params.require(:trackee).permit(:name, :email)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token
  protect_from_forgery :except => :create 

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)


    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        UserMailer.welcome_email(@user).deliver
        flash[:success] = "Cool. See you soon."
        format.html { redirect_to(:back) }
       #format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :login)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/trackees_helper.rb
module TrackeesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
  <title>Qawmly</title>
  <!--[if lt IE 9]>
  <script scr="http://html5shim.googlecode.com/svn/trunk/html5.js" type=text/javascript"></script>
  <![endif]-->
  
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="http://pupunzi.com/mb.components/mb.YTPlayer/demo/inc/jquery.mb.YTPlayer.js"></script>
  <link href='http://fonts.googleapis.com/css?family=Buenard:700' rel='stylesheet' type='text/css'>

  <link href="http://vjs.zencdn.net/4.6/video-js.css" rel="stylesheet">
  <script src="http://vjs.zencdn.net/4.6/video.js"></script>

  <link href="assets/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="assets/css/video-default.css" rel="stylesheet">
<script type="text/javascript" src="assets/js/jquery-1.8.1.min.js"></script>
<script type="text/javascript" src="assets/js/jquery.video-ui.js"></script>



</head>
<header style="max-height: 30px;">
    <nav class="navbar navbar-inverse" role="navigation">
    <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      
  
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
 
        <img src="SVLogo51x52square.png" class="img-responsive" alt="responsive image" bgcolor="#333333">
          
    
    </div>
  
     
    <ul class="nav nabar-nav navbar-left">
        
     </ul>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      

       
     
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#Features">Features</a></li>
        <li><a href="#WhatIsQawm">What is Qawm?</a></li>
        <li><a href="#AboutUs">About Us</a></li>
        <li><a href="#ContactUs">Contact</a></li>

       
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  </header>
<body>
<%= yield %>
</div>

   <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>

     <script src="http://pupunzi.com/mb.components/mb.YTPlayer/demo/inc/jquery.mb.YTPlayer.js"></script>
    <script type="text/javascript">
$(document).ready(function () {

    $(".player").mb_YTPlayer();

});</script>

<script type="text/javascript">
  // Once the video is ready
  _V_("example_video_1").ready(function(){

    var myPlayer = this;    // Store the video object
    var aspectRatio = 1; // Make up an aspect ratio

    function resizeVideoJS(){
      // Get the parent element's actual width
      var width = document.getElementById(myPlayer.id).parentElement.offsetWidth;
      // Set width to fill parent element, Set height
      myPlayer.width(width).height( width * aspectRatio );
    }

    resizeVideoJS(); // Initialize the function
    window.onresize = resizeVideoJS; // Call the function on resize
  });
</script>


</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/trackees/_form.html.erb
<%= form_for(@trackee) do |f| %>
  <% if @trackee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trackee.errors.count, "error") %> prohibited this trackee from being saved:</h2>

      <ul>
      <% @trackee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trackees/edit.html.erb
<h1>Editing trackee</h1>

<%= render 'form' %>

<%= link_to 'Show', @trackee %> |
<%= link_to 'Back', trackees_path %>

app/views/trackees/index.html.erb
<h1>Listing trackees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @trackees.each do |trackee| %>
      <tr>
        <td><%= trackee.name %></td>
        <td><%= trackee.email %></td>
        <td><%= link_to 'Show', trackee %></td>
        <td><%= link_to 'Edit', edit_trackee_path(trackee) %></td>
        <td><%= link_to 'Destroy', trackee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trackee', new_trackee_path %>

app/views/trackees/new.html.erb
<h1>New trackee</h1>

<%= render 'form' %>

<%= link_to 'Back', trackees_path %>

app/views/trackees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trackee.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @trackee.email %>
</p>

<%= link_to 'Edit', edit_trackee_path(@trackee) %> |
<%= link_to 'Back', trackees_path %>

app/views/users/_form.html.erb
<%= form_for(User.new) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Login</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.login %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/_form.html.erb
  

  <%= bootstrap_form_for(User.new) do |f| %>
      <%= f.email_field :name, class: "form-control", control_col: "col-xs-8", placeholder: "Name", label:"Name" %>
      <%= f.name_field :email, class: "form-control", control_col: "col-xs-8", placeholder: "Email", label: "Email" %>
 
      <%= f.submit "Keep Me Updated", class:"btn btn-success", control_col: "col-xs-offset-2 col-xs-4"  %>
<% end %>

 

 